# Generated by Django 4.1.5 on 2023-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("telefone1", models.CharField(blank=True, max_length=15, null=True)),
                ("telefone2", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
